{{- if and .Values.pingfederate.clustering.autoscaling.enabled .Values.pingfederate.clustering.enabled -}}
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  labels:
    app.kubernetes.io/name: {{ include "pingfederate.name" . }}-engine
    helm.sh/chart: {{ include "pingfederate.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  name: {{ include "pingfederate.fullname" . }}-engine
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "pingfederate.fullname" . }}-engine
  minReplicas: {{ .Values.pingfederate.clustering.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.pingfederate.clustering.autoscaling.maxReplicas }}
  metrics:
  {{- with .Values.pingfederate.clustering.autoscaling.targetCPUUtilizationPercentage }}
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: {{ . }}
  {{- end }}
  {{- with .Values.pingfederate.clustering.autoscaling.targetMemoryUtilizationPercentage }}
  - type: Resource 
    resource: 
      name: memory 
      target:
        type: Utilization
        averageUtilization: {{ . }}
  {{- end }}
  {{- with .Values.pingfederate.clustering.autoscalingTemplate }}
{{- toYaml . | nindent 2 }}
  {{- end }}
{{- end }}